import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#121212' },
    authContainer: { flex: 1, backgroundColor: '#121212', justifyContent: 'center', padding: 20 },
      authCard: { backgroundColor: '#1e1e1e', padding: 20, borderRadius: 12, borderBottomWidth: 3, borderBottomColor: '#e50914' },
        authLogo: { fontSize: 24, fontWeight: 'bold', color: '#e50914', textAlign: 'center' },
          authSub: { color: '#aaa', textAlign: 'center', fontSize: 12, marginBottom: 20 },
            header: { flexDirection: 'row', justifyContent: 'space-between', padding: 12, backgroundColor: '#1e1e1e', alignItems: 'center' },
              logoText: { color: '#e50914', fontSize: 18, fontWeight: 'bold' },
                walletBadge: { backgroundColor: '#262626', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 16 },
                  walletText: { color: '#00ff87', fontWeight: 'bold', fontSize: 13 },
                    tabBar: { flexDirection: 'row', backgroundColor: '#1a1a1a', borderBottomWidth: 1, borderBottomColor: '#333' },
                      tabItem: { flex: 1, paddingVertical: 10, alignItems: 'center' },
                        activeTab: { borderBottomWidth: 2, borderBottomColor: '#e50914' },
                          tabText: { color: '#fff', fontSize: 11, fontWeight: 'bold' },
                            listSection: { flex: 1, padding: 10 },
                              filterChip: { backgroundColor: '#262626', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6, marginRight: 6 },
                                activeFilterChip: { backgroundColor: '#e50914' },
                                  card: { backgroundColor: '#1e1e1e', borderRadius: 10, marginBottom: 14, overflow: 'hidden' },
                                    bannerImage: { width: '100%', height: 130 },
                                      cardDetails: { padding: 12 },
                                        movieTitle: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
                                          catBadge: { color: '#aaa', backgroundColor: '#262626', fontSize: 10, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
                                            prizeBox: { backgroundColor: '#262626', padding: 8, borderRadius: 6, marginVertical: 8 },
                                              prizeAmount: { color: '#00ff87', fontSize: 18, fontWeight: 'bold' },
                                                rankText: { color: '#ccc', fontSize: 10 },
                                                  actionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 6 },
                                                    predictBtn: { backgroundColor: '#e50914', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 6 },
                                                      closedBtn: { backgroundColor: '#444', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 6 },
                                                        viewBoardBtn: { backgroundColor: '#262626', borderWidth: 1, borderColor: '#555', paddingHorizontal: 10, paddingVertical: 8, borderRadius: 6 },
                                                          predictBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 11 },
                                                            label: { color: '#ccc', fontSize: 12, marginTop: 10 },
                                                              input: { backgroundColor: '#2a2a2a', color: '#fff', padding: 10, borderRadius: 6, marginTop: 4 },
                                                                primaryBtn: { backgroundColor: '#e50914', padding: 12, borderRadius: 6, alignItems: 'center', marginTop: 15 },
                                                                  primaryBtnText: { color: '#fff', fontWeight: 'bold' },
                                                                    adminCard: { backgroundColor: '#1e1e1e', padding: 16, borderRadius: 10 },
                                                                      adminHead: { color: '#e50914', fontSize: 16, fontWeight: 'bold' },
                                                                        boardCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#1e1e1e', padding: 12, borderRadius: 8, marginBottom: 8 },
                                                                          rankCircle: { width: 30, height: 30, borderRadius: 15, backgroundColor: '#262626', justifyContent: 'center', alignItems: 'center' },
                                                                            modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'center', alignItems: 'center' },
                                                                              modalContent: { width: '90%', backgroundColor: '#1e1e1e', padding: 16, borderRadius: 12, maxHeight: '80%' }
                                                                              });
                                                                              